(function(){
  const db=window.supabase.createClient('https://xulnkdrgjgajmcqntwga.supabase.co','sb_publishable_J2OrXvOnQXxrf5t3XPmigg_5ULrsWO2');
  (function loadI18n(){if(window.choirI18n||document.querySelector('script[data-choir-i18n]'))return;const s=document.createElement('script');s.src='./i18n.js?v=20260905';s.async=false;s.setAttribute('data-choir-i18n','1');document.head.appendChild(s)})();
  async function getRole(){const {data,error}=await db.rpc('get_my_role');if(error)throw error;return data||null}
  async function check(){const {data:{session}}=await db.auth.getSession();if(!session)return null;const r=await getRole();if(!['admin','super_admin','member'].includes(r)){await db.auth.signOut();return null}if(location.pathname.endsWith('/dashboard.html')&&r==='member')location.replace('member-dashboard.html');if(location.pathname.endsWith('/member-dashboard.html')&&['admin','super_admin'].includes(r))location.replace('dashboard.html');if(location.pathname.endsWith('/attendance.html')&&r==='member'){location.replace('member-attendance.html');return null}document.querySelectorAll('[data-super-admin-only]').forEach(e=>{if(r!=='super_admin')e.remove()});document.querySelectorAll('[data-admin-only]').forEach(e=>{if(!['admin','super_admin'].includes(r))e.remove()});return r}
  window.KWAYA_AUTH={db,getRole,isAdmin:async()=>['admin','super_admin'].includes(await getRole()),isSuperAdmin:async()=>await getRole()==='super_admin',isMember:async()=>await getRole()==='member',check};
  db.auth.onAuthStateChange(event=>{if(event==='SIGNED_OUT'&&!location.pathname.endsWith('/login.html'))location.replace('login.html')});
  function addMemberBooksLink(){if(!location.pathname.endsWith('/member-dashboard.html'))return;const q=document.querySelector('.quick');if(!q)return;if(q.querySelector('[href="member-song-books.html"]'))return;const old=q.querySelector('[href="song-books.html"]');if(old)old.remove();const a=document.createElement('a');a.href='member-song-books.html';a.innerHTML='📚<br>Vitabu vya Nyimbo';q.appendChild(a)}
  function addMemberAttendanceLink(){if(!location.pathname.endsWith('/member-dashboard.html'))return;const q=document.querySelector('.quick');if(!q||q.querySelector('[href="member-attendance.html"]'))return;const a=document.createElement('a');a.href='member-attendance.html';a.innerHTML='📋<br>Mahudhurio';q.appendChild(a)}
  function loadMemberAttendanceFix(){if(!location.pathname.endsWith('/member-attendance.html'))return;const s=document.createElement('script');s.src='./member-attendance-fix.js?v=20260905';document.head.appendChild(s)}
  function ensureAdminAttendanceAuth(role){if(!['admin','super_admin'].includes(role)||!location.pathname.endsWith('/attendance.html'))return;if(sessionStorage.getItem('kwaya_attendance_auth_ready')==='1'){sessionStorage.removeItem('kwaya_attendance_auth_ready');return}sessionStorage.setItem('kwaya_attendance_auth_ready','1');location.reload()}
  check().then(role=>{if(!role)return;ensureAdminAttendanceAuth(role);if(location.pathname.endsWith('/dashboard.html')){const runDashboard=()=>{if(typeof window.load==='function')window.load().catch(e=>{console.error('Dashboard load after auth:',e);const s=document.getElementById('linkStatus');if(s)s.textContent='Hitilafu: '+e.message})};if(typeof window.load==='function')runDashboard();else document.addEventListener('DOMContentLoaded',runDashboard,{once:true})}if(location.pathname.endsWith('/member-profile.html')){const s=document.createElement('script');s.src='./profile-loader.js?v=3';document.head.appendChild(s)}if(location.pathname.endsWith('/sacraments.html')){const s=document.createElement('script');s.src='./sacraments-filter.js?v=1';document.head.appendChild(s)}if(role==='member'&&location.pathname.endsWith('/member-dashboard.html')){addMemberBooksLink();addMemberAttendanceLink();const s=document.createElement('script');s.src='./member-songs-fix.js?v=20260905b';document.head.appendChild(s)}if(role==='member'&&location.pathname.endsWith('/member-attendance.html'))loadMemberAttendanceFix()}).catch(e=>console.error('Auth guard:',e));
})();